// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tuning.proto

#include "tuning.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace protobuf_msgs {
PROTOBUF_CONSTEXPR TuningState_Parameter_NumberParameter::TuningState_Parameter_NumberParameter(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_)*/0
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TuningState_Parameter_NumberParameterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TuningState_Parameter_NumberParameterDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TuningState_Parameter_NumberParameterDefaultTypeInternal() {}
  union {
    TuningState_Parameter_NumberParameter _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TuningState_Parameter_NumberParameterDefaultTypeInternal _TuningState_Parameter_NumberParameter_default_instance_;
PROTOBUF_CONSTEXPR TuningState_Parameter_StringParameter::TuningState_Parameter_StringParameter(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.key_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.value_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TuningState_Parameter_StringParameterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TuningState_Parameter_StringParameterDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TuningState_Parameter_StringParameterDefaultTypeInternal() {}
  union {
    TuningState_Parameter_StringParameter _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TuningState_Parameter_StringParameterDefaultTypeInternal _TuningState_Parameter_StringParameter_default_instance_;
PROTOBUF_CONSTEXPR TuningState_Parameter::TuningState_Parameter(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.parameter_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_._oneof_case_)*/{}} {}
struct TuningState_ParameterDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TuningState_ParameterDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TuningState_ParameterDefaultTypeInternal() {}
  union {
    TuningState_Parameter _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TuningState_ParameterDefaultTypeInternal _TuningState_Parameter_default_instance_;
PROTOBUF_CONSTEXPR TuningState::TuningState(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.dynamicparameters_)*/{}
  , /*decltype(_impl_.timestamp_)*/uint64_t{0u}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct TuningStateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR TuningStateDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~TuningStateDefaultTypeInternal() {}
  union {
    TuningState _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 TuningStateDefaultTypeInternal _TuningState_default_instance_;
}  // namespace protobuf_msgs
static ::_pb::Metadata file_level_metadata_tuning_2eproto[4];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_tuning_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_tuning_2eproto = nullptr;

const uint32_t TableStruct_tuning_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState_Parameter_NumberParameter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState_Parameter_NumberParameter, _impl_.key_),
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState_Parameter_NumberParameter, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState_Parameter_StringParameter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState_Parameter_StringParameter, _impl_.key_),
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState_Parameter_StringParameter, _impl_.value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState_Parameter, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState_Parameter, _impl_._oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  ::_pbi::kInvalidFieldOffsetTag,
  ::_pbi::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState_Parameter, _impl_.parameter_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::protobuf_msgs::TuningState, _impl_.dynamicparameters_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::protobuf_msgs::TuningState_Parameter_NumberParameter)},
  { 8, -1, -1, sizeof(::protobuf_msgs::TuningState_Parameter_StringParameter)},
  { 16, -1, -1, sizeof(::protobuf_msgs::TuningState_Parameter)},
  { 25, -1, -1, sizeof(::protobuf_msgs::TuningState)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::protobuf_msgs::_TuningState_Parameter_NumberParameter_default_instance_._instance,
  &::protobuf_msgs::_TuningState_Parameter_StringParameter_default_instance_._instance,
  &::protobuf_msgs::_TuningState_Parameter_default_instance_._instance,
  &::protobuf_msgs::_TuningState_default_instance_._instance,
};

const char descriptor_table_protodef_tuning_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\014tuning.proto\022\rprotobuf_msgs\"\352\002\n\013Tuning"
  "State\022\021\n\ttimestamp\030\001 \001(\004\022\?\n\021dynamicParam"
  "eters\030\002 \003(\0132$.protobuf_msgs.TuningState."
  "Parameter\032\206\002\n\tParameter\022F\n\006number\030\001 \001(\0132"
  "4.protobuf_msgs.TuningState.Parameter.Nu"
  "mberParameterH\000\022F\n\006string\030\003 \001(\01324.protob"
  "uf_msgs.TuningState.Parameter.StringPara"
  "meterH\000\032-\n\017NumberParameter\022\013\n\003key\030\001 \001(\t\022"
  "\r\n\005value\030\002 \001(\002\032-\n\017StringParameter\022\013\n\003key"
  "\030\001 \001(\t\022\r\n\005value\030\002 \001(\tB\013\n\tparameterB\017Z\ras"
  "e/pb_tuningb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_tuning_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_tuning_2eproto = {
    false, false, 419, descriptor_table_protodef_tuning_2eproto,
    "tuning.proto",
    &descriptor_table_tuning_2eproto_once, nullptr, 0, 4,
    schemas, file_default_instances, TableStruct_tuning_2eproto::offsets,
    file_level_metadata_tuning_2eproto, file_level_enum_descriptors_tuning_2eproto,
    file_level_service_descriptors_tuning_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_tuning_2eproto_getter() {
  return &descriptor_table_tuning_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_tuning_2eproto(&descriptor_table_tuning_2eproto);
namespace protobuf_msgs {

// ===================================================================

class TuningState_Parameter_NumberParameter::_Internal {
 public:
};

TuningState_Parameter_NumberParameter::TuningState_Parameter_NumberParameter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf_msgs.TuningState.Parameter.NumberParameter)
}
TuningState_Parameter_NumberParameter::TuningState_Parameter_NumberParameter(const TuningState_Parameter_NumberParameter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TuningState_Parameter_NumberParameter* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_key().empty()) {
    _this->_impl_.key_.Set(from._internal_key(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.value_ = from._impl_.value_;
  // @@protoc_insertion_point(copy_constructor:protobuf_msgs.TuningState.Parameter.NumberParameter)
}

inline void TuningState_Parameter_NumberParameter::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){}
    , decltype(_impl_.value_){0}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TuningState_Parameter_NumberParameter::~TuningState_Parameter_NumberParameter() {
  // @@protoc_insertion_point(destructor:protobuf_msgs.TuningState.Parameter.NumberParameter)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TuningState_Parameter_NumberParameter::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.key_.Destroy();
}

void TuningState_Parameter_NumberParameter::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TuningState_Parameter_NumberParameter::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf_msgs.TuningState.Parameter.NumberParameter)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.key_.ClearToEmpty();
  _impl_.value_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TuningState_Parameter_NumberParameter::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf_msgs.TuningState.Parameter.NumberParameter.key"));
        } else
          goto handle_unusual;
        continue;
      // float value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 21)) {
          _impl_.value_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TuningState_Parameter_NumberParameter::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf_msgs.TuningState.Parameter.NumberParameter)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_key().data(), static_cast<int>(this->_internal_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf_msgs.TuningState.Parameter.NumberParameter.key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_key(), target);
  }

  // float value = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_value = this->_internal_value();
  uint32_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(2, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf_msgs.TuningState.Parameter.NumberParameter)
  return target;
}

size_t TuningState_Parameter_NumberParameter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf_msgs.TuningState.Parameter.NumberParameter)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  // float value = 2;
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_value = this->_internal_value();
  uint32_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    total_size += 1 + 4;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TuningState_Parameter_NumberParameter::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TuningState_Parameter_NumberParameter::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TuningState_Parameter_NumberParameter::GetClassData() const { return &_class_data_; }


void TuningState_Parameter_NumberParameter::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TuningState_Parameter_NumberParameter*>(&to_msg);
  auto& from = static_cast<const TuningState_Parameter_NumberParameter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf_msgs.TuningState.Parameter.NumberParameter)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  static_assert(sizeof(uint32_t) == sizeof(float), "Code assumes uint32_t and float are the same size.");
  float tmp_value = from._internal_value();
  uint32_t raw_value;
  memcpy(&raw_value, &tmp_value, sizeof(tmp_value));
  if (raw_value != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TuningState_Parameter_NumberParameter::CopyFrom(const TuningState_Parameter_NumberParameter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf_msgs.TuningState.Parameter.NumberParameter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TuningState_Parameter_NumberParameter::IsInitialized() const {
  return true;
}

void TuningState_Parameter_NumberParameter::InternalSwap(TuningState_Parameter_NumberParameter* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.key_, lhs_arena,
      &other->_impl_.key_, rhs_arena
  );
  swap(_impl_.value_, other->_impl_.value_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TuningState_Parameter_NumberParameter::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tuning_2eproto_getter, &descriptor_table_tuning_2eproto_once,
      file_level_metadata_tuning_2eproto[0]);
}

// ===================================================================

class TuningState_Parameter_StringParameter::_Internal {
 public:
};

TuningState_Parameter_StringParameter::TuningState_Parameter_StringParameter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf_msgs.TuningState.Parameter.StringParameter)
}
TuningState_Parameter_StringParameter::TuningState_Parameter_StringParameter(const TuningState_Parameter_StringParameter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TuningState_Parameter_StringParameter* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_key().empty()) {
    _this->_impl_.key_.Set(from._internal_key(), 
      _this->GetArenaForAllocation());
  }
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_value().empty()) {
    _this->_impl_.value_.Set(from._internal_value(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:protobuf_msgs.TuningState.Parameter.StringParameter)
}

inline void TuningState_Parameter_StringParameter::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){}
    , decltype(_impl_.value_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.key_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.value_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

TuningState_Parameter_StringParameter::~TuningState_Parameter_StringParameter() {
  // @@protoc_insertion_point(destructor:protobuf_msgs.TuningState.Parameter.StringParameter)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TuningState_Parameter_StringParameter::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.key_.Destroy();
  _impl_.value_.Destroy();
}

void TuningState_Parameter_StringParameter::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TuningState_Parameter_StringParameter::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf_msgs.TuningState.Parameter.StringParameter)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.key_.ClearToEmpty();
  _impl_.value_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TuningState_Parameter_StringParameter::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string key = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_key();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf_msgs.TuningState.Parameter.StringParameter.key"));
        } else
          goto handle_unusual;
        continue;
      // string value = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_value();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "protobuf_msgs.TuningState.Parameter.StringParameter.value"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TuningState_Parameter_StringParameter::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf_msgs.TuningState.Parameter.StringParameter)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_key().data(), static_cast<int>(this->_internal_key().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf_msgs.TuningState.Parameter.StringParameter.key");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_key(), target);
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_value().data(), static_cast<int>(this->_internal_value().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "protobuf_msgs.TuningState.Parameter.StringParameter.value");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf_msgs.TuningState.Parameter.StringParameter)
  return target;
}

size_t TuningState_Parameter_StringParameter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf_msgs.TuningState.Parameter.StringParameter)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_key());
  }

  // string value = 2;
  if (!this->_internal_value().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_value());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TuningState_Parameter_StringParameter::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TuningState_Parameter_StringParameter::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TuningState_Parameter_StringParameter::GetClassData() const { return &_class_data_; }


void TuningState_Parameter_StringParameter::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TuningState_Parameter_StringParameter*>(&to_msg);
  auto& from = static_cast<const TuningState_Parameter_StringParameter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf_msgs.TuningState.Parameter.StringParameter)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  if (!from._internal_value().empty()) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TuningState_Parameter_StringParameter::CopyFrom(const TuningState_Parameter_StringParameter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf_msgs.TuningState.Parameter.StringParameter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TuningState_Parameter_StringParameter::IsInitialized() const {
  return true;
}

void TuningState_Parameter_StringParameter::InternalSwap(TuningState_Parameter_StringParameter* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.key_, lhs_arena,
      &other->_impl_.key_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.value_, lhs_arena,
      &other->_impl_.value_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata TuningState_Parameter_StringParameter::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tuning_2eproto_getter, &descriptor_table_tuning_2eproto_once,
      file_level_metadata_tuning_2eproto[1]);
}

// ===================================================================

class TuningState_Parameter::_Internal {
 public:
  static const ::protobuf_msgs::TuningState_Parameter_NumberParameter& number(const TuningState_Parameter* msg);
  static const ::protobuf_msgs::TuningState_Parameter_StringParameter& string(const TuningState_Parameter* msg);
};

const ::protobuf_msgs::TuningState_Parameter_NumberParameter&
TuningState_Parameter::_Internal::number(const TuningState_Parameter* msg) {
  return *msg->_impl_.parameter_.number_;
}
const ::protobuf_msgs::TuningState_Parameter_StringParameter&
TuningState_Parameter::_Internal::string(const TuningState_Parameter* msg) {
  return *msg->_impl_.parameter_.string_;
}
void TuningState_Parameter::set_allocated_number(::protobuf_msgs::TuningState_Parameter_NumberParameter* number) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_parameter();
  if (number) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(number);
    if (message_arena != submessage_arena) {
      number = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, number, submessage_arena);
    }
    set_has_number();
    _impl_.parameter_.number_ = number;
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf_msgs.TuningState.Parameter.number)
}
void TuningState_Parameter::set_allocated_string(::protobuf_msgs::TuningState_Parameter_StringParameter* string) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  clear_parameter();
  if (string) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(string);
    if (message_arena != submessage_arena) {
      string = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, string, submessage_arena);
    }
    set_has_string();
    _impl_.parameter_.string_ = string;
  }
  // @@protoc_insertion_point(field_set_allocated:protobuf_msgs.TuningState.Parameter.string)
}
TuningState_Parameter::TuningState_Parameter(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf_msgs.TuningState.Parameter)
}
TuningState_Parameter::TuningState_Parameter(const TuningState_Parameter& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TuningState_Parameter* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.parameter_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  clear_has_parameter();
  switch (from.parameter_case()) {
    case kNumber: {
      _this->_internal_mutable_number()->::protobuf_msgs::TuningState_Parameter_NumberParameter::MergeFrom(
          from._internal_number());
      break;
    }
    case kString: {
      _this->_internal_mutable_string()->::protobuf_msgs::TuningState_Parameter_StringParameter::MergeFrom(
          from._internal_string());
      break;
    }
    case PARAMETER_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:protobuf_msgs.TuningState.Parameter)
}

inline void TuningState_Parameter::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.parameter_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , /*decltype(_impl_._oneof_case_)*/{}
  };
  clear_has_parameter();
}

TuningState_Parameter::~TuningState_Parameter() {
  // @@protoc_insertion_point(destructor:protobuf_msgs.TuningState.Parameter)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TuningState_Parameter::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (has_parameter()) {
    clear_parameter();
  }
}

void TuningState_Parameter::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TuningState_Parameter::clear_parameter() {
// @@protoc_insertion_point(one_of_clear_start:protobuf_msgs.TuningState.Parameter)
  switch (parameter_case()) {
    case kNumber: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.parameter_.number_;
      }
      break;
    }
    case kString: {
      if (GetArenaForAllocation() == nullptr) {
        delete _impl_.parameter_.string_;
      }
      break;
    }
    case PARAMETER_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = PARAMETER_NOT_SET;
}


void TuningState_Parameter::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf_msgs.TuningState.Parameter)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_parameter();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TuningState_Parameter::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .protobuf_msgs.TuningState.Parameter.NumberParameter number = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_number(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .protobuf_msgs.TuningState.Parameter.StringParameter string = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_string(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TuningState_Parameter::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf_msgs.TuningState.Parameter)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .protobuf_msgs.TuningState.Parameter.NumberParameter number = 1;
  if (_internal_has_number()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::number(this),
        _Internal::number(this).GetCachedSize(), target, stream);
  }

  // .protobuf_msgs.TuningState.Parameter.StringParameter string = 3;
  if (_internal_has_string()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, _Internal::string(this),
        _Internal::string(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf_msgs.TuningState.Parameter)
  return target;
}

size_t TuningState_Parameter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf_msgs.TuningState.Parameter)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (parameter_case()) {
    // .protobuf_msgs.TuningState.Parameter.NumberParameter number = 1;
    case kNumber: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.parameter_.number_);
      break;
    }
    // .protobuf_msgs.TuningState.Parameter.StringParameter string = 3;
    case kString: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
          *_impl_.parameter_.string_);
      break;
    }
    case PARAMETER_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TuningState_Parameter::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TuningState_Parameter::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TuningState_Parameter::GetClassData() const { return &_class_data_; }


void TuningState_Parameter::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TuningState_Parameter*>(&to_msg);
  auto& from = static_cast<const TuningState_Parameter&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf_msgs.TuningState.Parameter)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.parameter_case()) {
    case kNumber: {
      _this->_internal_mutable_number()->::protobuf_msgs::TuningState_Parameter_NumberParameter::MergeFrom(
          from._internal_number());
      break;
    }
    case kString: {
      _this->_internal_mutable_string()->::protobuf_msgs::TuningState_Parameter_StringParameter::MergeFrom(
          from._internal_string());
      break;
    }
    case PARAMETER_NOT_SET: {
      break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TuningState_Parameter::CopyFrom(const TuningState_Parameter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf_msgs.TuningState.Parameter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TuningState_Parameter::IsInitialized() const {
  return true;
}

void TuningState_Parameter::InternalSwap(TuningState_Parameter* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.parameter_, other->_impl_.parameter_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata TuningState_Parameter::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tuning_2eproto_getter, &descriptor_table_tuning_2eproto_once,
      file_level_metadata_tuning_2eproto[2]);
}

// ===================================================================

class TuningState::_Internal {
 public:
};

TuningState::TuningState(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:protobuf_msgs.TuningState)
}
TuningState::TuningState(const TuningState& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  TuningState* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.dynamicparameters_){from._impl_.dynamicparameters_}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _this->_impl_.timestamp_ = from._impl_.timestamp_;
  // @@protoc_insertion_point(copy_constructor:protobuf_msgs.TuningState)
}

inline void TuningState::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.dynamicparameters_){arena}
    , decltype(_impl_.timestamp_){uint64_t{0u}}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

TuningState::~TuningState() {
  // @@protoc_insertion_point(destructor:protobuf_msgs.TuningState)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void TuningState::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.dynamicparameters_.~RepeatedPtrField();
}

void TuningState::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void TuningState::Clear() {
// @@protoc_insertion_point(message_clear_start:protobuf_msgs.TuningState)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.dynamicparameters_.Clear();
  _impl_.timestamp_ = uint64_t{0u};
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* TuningState::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 timestamp = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.timestamp_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // repeated .protobuf_msgs.TuningState.Parameter dynamicParameters = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_dynamicparameters(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* TuningState::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:protobuf_msgs.TuningState)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 timestamp = 1;
  if (this->_internal_timestamp() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_timestamp(), target);
  }

  // repeated .protobuf_msgs.TuningState.Parameter dynamicParameters = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_dynamicparameters_size()); i < n; i++) {
    const auto& repfield = this->_internal_dynamicparameters(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protobuf_msgs.TuningState)
  return target;
}

size_t TuningState::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protobuf_msgs.TuningState)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .protobuf_msgs.TuningState.Parameter dynamicParameters = 2;
  total_size += 1UL * this->_internal_dynamicparameters_size();
  for (const auto& msg : this->_impl_.dynamicparameters_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // uint64 timestamp = 1;
  if (this->_internal_timestamp() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData TuningState::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    TuningState::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*TuningState::GetClassData() const { return &_class_data_; }


void TuningState::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<TuningState*>(&to_msg);
  auto& from = static_cast<const TuningState&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:protobuf_msgs.TuningState)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.dynamicparameters_.MergeFrom(from._impl_.dynamicparameters_);
  if (from._internal_timestamp() != 0) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void TuningState::CopyFrom(const TuningState& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protobuf_msgs.TuningState)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool TuningState::IsInitialized() const {
  return true;
}

void TuningState::InternalSwap(TuningState* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.dynamicparameters_.InternalSwap(&other->_impl_.dynamicparameters_);
  swap(_impl_.timestamp_, other->_impl_.timestamp_);
}

::PROTOBUF_NAMESPACE_ID::Metadata TuningState::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_tuning_2eproto_getter, &descriptor_table_tuning_2eproto_once,
      file_level_metadata_tuning_2eproto[3]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf_msgs
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::protobuf_msgs::TuningState_Parameter_NumberParameter*
Arena::CreateMaybeMessage< ::protobuf_msgs::TuningState_Parameter_NumberParameter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf_msgs::TuningState_Parameter_NumberParameter >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf_msgs::TuningState_Parameter_StringParameter*
Arena::CreateMaybeMessage< ::protobuf_msgs::TuningState_Parameter_StringParameter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf_msgs::TuningState_Parameter_StringParameter >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf_msgs::TuningState_Parameter*
Arena::CreateMaybeMessage< ::protobuf_msgs::TuningState_Parameter >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf_msgs::TuningState_Parameter >(arena);
}
template<> PROTOBUF_NOINLINE ::protobuf_msgs::TuningState*
Arena::CreateMaybeMessage< ::protobuf_msgs::TuningState >(Arena* arena) {
  return Arena::CreateMessageInternal< ::protobuf_msgs::TuningState >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
